services:

  postgres:
    image: pgvector/pgvector:pg16

    container_name: aip-postgres

    restart: always

    environment:
      POSTGRES_USER: aip
      POSTGRES_PASSWORD: aip123
      POSTGRES_DB: aipdb

    ports:
      - "5432:5432"

    volumes:
      - ../postgres:/var/lib/postgresql/data

  neo4j:

    image: neo4j:5

    container_name: aip-neo4j

    restart: always

    environment:
      NEO4J_AUTH: neo4j/password123

    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - ../neo4j:/data

  redis:

    image: redis:7

    container_name: aip-redis

    restart: always

    ports:
      - "6379:6379"

    volumes:
      - ../redis:/data

  analytics-postgres:

    image: postgres:16

    container_name: analytics-source-db

    restart: always

    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics123
      POSTGRES_DB: treasurydb

    ports:
      - "5433:5432"

    volumes:
      - ../analytics-data:/var/lib/postgresql/data