"""
Generic visualization planner renderer and markdown converter for AIP sub-agents.
"""

import html
from typing import Dict, Any, List, Tuple


def _numeric(row: Dict[str, Any], key: str) -> float:
    try:
        return float(row.get(key) or 0)
    except (TypeError, ValueError):
        return 0.0


def _format_currency(value: float) -> str:
    """Format large enterprise amounts for stakeholder visual summaries."""
    abs_value = abs(value)
    if abs_value >= 1_000_000_000:
        return f"${value / 1_000_000_000:.2f}B"
    if abs_value >= 1_000_000:
        return f"${value / 1_000_000:.1f}M"
    if abs_value >= 1_000:
        return f"${value / 1_000:.1f}K"
    return f"${value:,.0f}"


def render_premium_visuals(viz_plan: Dict[str, Any], executed_queries: List[Dict[str, Any]]) -> str:
    """Renders sleek glassmorphic visualizations matching the visual plan.

    Args:
        viz_plan: The visualization plan generated by the Visualization Planner Agent.
        executed_queries: The list of executed query dictionaries containing rows and labels.

    Returns:
        Premium styled glassmorphic HTML visual snippet.
    """
    if not viz_plan or not viz_plan.get('has_visual') or not viz_plan.get('visuals'):
        return ""
        
    query_map = {q['label']: q['rows'] for q in executed_queries if q.get('rows')}
    html_blocks = []
    
    for viz in viz_plan['visuals']:
        vtype = viz.get('type')
        title = viz.get('title', 'BI Snapshot')
        desc = viz.get('description', '')
        dkey = viz.get('data_key')
        config = viz.get('config', {})
        
        rows = query_map.get(dkey)
        if not rows:
            continue
            
        color_scheme = config.get('color_scheme', 'indigo')
        colors = {
            'emerald': {'bg': 'rgba(16, 185, 129, 0.1)', 'border': '#10b981', 'accent': '#059669'},
            'indigo': {'bg': 'rgba(99, 102, 241, 0.1)', 'border': '#6366f1', 'accent': '#4f46e5'},
            'amber': {'bg': 'rgba(245, 158, 11, 0.1)', 'border': '#f59e0b', 'accent': '#d97706'},
            'rose': {'bg': 'rgba(244, 63, 94, 0.1)', 'border': '#f43f5e', 'accent': '#e11d48'},
        }.get(color_scheme, {'bg': 'rgba(99, 102, 241, 0.1)', 'border': '#6366f1', 'accent': '#4f46e5'})
        
        card = [
            f"<div class='convbi-visual-card' style='border-left: 4px solid {colors['border']}; margin-top: 1.5rem; padding: 1.25rem; border-radius: 12px; background: var(--bg-card, rgba(255,255,255,0.7)); backdrop-filter: blur(10px); box-shadow: 0 4px 20px rgba(0,0,0,0.05); border: 1px solid rgba(0,0,0,0.06);'>"
            f"  <div class='convbi-visual-header' style='margin-bottom: 1.25rem;'>"
            f"    <span class='convbi-kicker' style='font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; color: {colors['border']}; font-weight: 700;'>Visual BI Insight</span>"
            f"    <h3 style='margin: 0.25rem 0 0.1rem 0; font-size: 1.15rem; font-weight: 800; color: var(--text-primary, #1e293b);'>{html.escape(title)}</h3>"
            f"    <p style='margin: 0; font-size: 0.85rem; color: var(--text-secondary, #64748b);'>{html.escape(desc)}</p>"
            f"  </div>"
        ]
        
        lbl_col = config.get('label_column')
        val_col = config.get('value_column')
        
        if not lbl_col or not val_col:
            first = rows[0]
            numeric_cols = [k for k, v in first.items() if isinstance(v, (int, float))]
            label_cols = [k for k in first.keys() if k not in numeric_cols]
            lbl_col = lbl_col or (label_cols[0] if label_cols else list(first.keys())[0])
            val_col = val_col or (numeric_cols[-1] if numeric_cols else list(first.keys())[-1])
            
        if vtype == 'bar':
            ranked = []
            for r in rows:
                val = _numeric(r, val_col)
                ranked.append((r, val))
            ranked = sorted(ranked, key=lambda x: x[1], reverse=True)[:8]
            max_value = max((abs(v) for _, v in ranked), default=1.0) or 1.0
            
            bars_html = []
            for r, val in ranked:
                lbl = str(r.get(lbl_col) or 'Unknown')
                width = max(5, min(100, abs(val) / max_value * 100))
                formatted_val = _format_currency(val) if 'balance' in val_col.lower() or 'amount' in val_col.lower() or 'limit' in val_col.lower() else f"{val:,.2f}" if isinstance(val, float) else f"{val:,}"
                
                bars_html.append(
                    f"<div class='convbi-bar-row' style='margin-bottom: 0.75rem;'>"
                    f"  <div class='convbi-bar-label' style='display: flex; justify-content: space-between; font-size: 0.85rem; margin-bottom: 0.25rem;'>"
                    f"    <span style='color: var(--text-primary, #334155); font-weight: 500;'>{html.escape(lbl)}</span>"
                    f"    <strong style='color: {colors['accent']};'>{html.escape(formatted_val)}</strong>"
                    f"  </div>"
                    f"  <div class='convbi-bar-track' style='background: var(--bg-track, #e2e8f0); height: 8px; border-radius: 4px; overflow: hidden;'>"
                    f"    <div class='convbi-bar-fill' style='width: {width:.1f}%; height: 100%; border-radius: 4px; background: {colors['border']}; transition: width 0.5s ease-in-out;'></div>"
                    f"  </div>"
                    f"</div>"
                )
            card.append("".join(bars_html))
            
        elif vtype == 'donut':
            total_sum = sum(_numeric(r, val_col) for r in rows) or 1.0
            sorted_rows = sorted(rows, key=lambda r: _numeric(r, val_col), reverse=True)
            top_segments = sorted_rows[:4]
            rest_sum = sum(_numeric(r, val_col) for r in sorted_rows[4:])
            
            segments = []
            for r in top_segments:
                segments.append({'lbl': str(r.get(lbl_col) or 'Unknown'), 'val': _numeric(r, val_col)})
            if rest_sum > 0:
                segments.append({'lbl': 'Others', 'val': rest_sum})
                
            svg_size = 120
            radius = 40
            circumference = 2 * 3.14159 * radius
            
            svg_html = [
                f"<div style='display: flex; align-items: center; justify-content: space-around; flex-wrap: wrap; gap: 1.25rem;'>"
                f"  <div style='position: relative; width: {svg_size}px; height: {svg_size}px;'>"
                f"    <svg viewBox='0 0 100 100' style='width: 100%; height: 100%; transform: rotate(-90deg);'>"
                f"      <circle cx='50' cy='50' r='{radius}' fill='transparent' stroke='var(--bg-track, #e2e8f0)' stroke-width='10' />"
            ]
            
            current_pct = 0.0
            segment_colors = [colors['border'], '#3b82f6', '#f59e0b', '#ec4899', '#10b981', '#64748b']
            
            legend_html = ["<div style='flex: 1; min-width: 150px; font-size: 0.85rem;'>"]
            
            for idx, seg in enumerate(segments):
                val_pct = seg['val'] / total_sum
                dash_array = f"{val_pct * circumference:.2f} {circumference:.2f}"
                dash_offset = f"{-current_pct * circumference:.2f}"
                stroke_color = segment_colors[idx % len(segment_colors)]
                
                svg_html.append(
                    f"      <circle cx='50' cy='50' r='{radius}' fill='transparent' "
                    f"              stroke='{stroke_color}' stroke-width='10' "
                    f"              stroke-dasharray='{dash_array}' stroke-dashoffset='{dash_offset}' "
                    f"              stroke-linecap='round' />"
                )
                
                formatted_val = _format_currency(seg['val']) if 'balance' in val_col.lower() or 'amount' in val_col.lower() else f"{seg['val']:,.1f}"
                legend_html.append(
                    f"<div style='display: flex; align-items: center; margin-bottom: 0.5rem;'>"
                    f"  <div style='width: 12px; height: 12px; border-radius: 3px; background: {stroke_color}; margin-right: 0.5rem;'></div>"
                    f"  <span style='color: var(--text-secondary, #475569); flex: 1;'>{html.escape(seg['lbl'])}</span>"
                    f"  <strong style='color: var(--text-primary, #0f172a);'>{formatted_val} ({val_pct*100:.1f}%)</strong>"
                    f"</div>"
                )
                current_pct += val_pct
                
            svg_html.append(
                f"    </svg>"
                f"    <div style='position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center; font-size: 0.75rem; font-weight: 700; color: var(--text-primary, #1e293b);'>"
                f"      <span>Total</span>"
                f"      <span style='font-size: 0.85rem; font-weight: 800; color: {colors['accent']};'>{_format_currency(total_sum) if 'balance' in val_col.lower() or 'amount' in val_col.lower() else f'{total_sum:,.0f}'}</span>"
                f"    </div>"
                f"  </div>"
            )
            legend_html.append("</div>")
            
            svg_html.append("".join(legend_html))
            svg_html.append("</div>")
            card.append("".join(svg_html))
            
        elif vtype == 'metrics_grid':
            grid_html = ["<div style='display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr)); gap: 1rem; margin-top: 0.5rem;'>"]
            for r in rows[:6]:
                lbl = str(r.get(lbl_col) or 'Unknown')
                val = _numeric(r, val_col)
                formatted_val = _format_currency(val) if 'balance' in val_col.lower() or 'amount' in val_col.lower() else f"{val:,.2f}" if isinstance(val, float) else f"{val:,}"
                
                grid_html.append(
                    f"<div class='convbi-metric-card' style='background: var(--bg-metric-card, rgba(0,0,0,0.02)); border: 1px solid rgba(0,0,0,0.03); padding: 0.85rem; border-radius: 8px; text-align: center;'>"
                    f"  <span style='display: block; font-size: 0.75rem; color: var(--text-secondary, #64748b); font-weight: 500; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;'>{html.escape(lbl)}</span>"
                    f"  <strong style='display: block; font-size: 1.15rem; font-weight: 800; color: {colors['accent']}; margin-top: 0.25rem;'>{html.escape(formatted_val)}</strong>"
                    f"</div>"
                )
            grid_html.append("</div>")
            card.append("".join(grid_html))
            
        elif vtype == 'table':
            cols = list(rows[0].keys())[:6]
            table_lines = [
                f"<div class='convbi-table-wrap' style='overflow-x: auto; border-radius: 8px; border: 1px solid rgba(0,0,0,0.06);'>"
                f"  <table style='width: 100%; border-collapse: collapse; text-align: left; font-size: 0.85rem;'>"
                f"    <thead>"
                f"      <tr style='background: var(--bg-table-head, #f8fafc); border-bottom: 1px solid rgba(0,0,0,0.06);'>"
            ]
            for c in cols:
                table_lines.append(f"        <th style='padding: 0.75rem; font-weight: 700; color: var(--text-secondary, #475569);'>{html.escape(c.replace('_', ' ').title())}</th>")
            table_lines.append("      </tr>\n    </thead>\n    <tbody>")
            
            for ridx, r in enumerate(rows[:10]):
                bg_style = "background: var(--bg-table-zebra, rgba(0,0,0,0.015));" if ridx % 2 == 1 else ""
                table_lines.append(f"      <tr style='border-bottom: 1px solid rgba(0,0,0,0.04); {bg_style}'>")
                for c in cols:
                    val = r.get(c)
                    if isinstance(val, (int, float)):
                        formatted_val = _format_currency(val) if 'balance' in c.lower() or 'amount' in c.lower() else f"{val:,.2f}" if isinstance(val, float) else f"{val:,}"
                    else:
                        formatted_val = str(val if val is not None else '')
                    table_lines.append(f"        <td style='padding: 0.75rem; color: var(--text-primary, #334155);'>{html.escape(formatted_val)}</td>")
                table_lines.append("      </tr>")
                
            table_lines.append("    </tbody>\n  </table>\n</div>")
            card.append("".join(table_lines))
            
        card.append("</div>")
        html_blocks.append("\n".join(card))
        
    return "\n\n".join(html_blocks)


def markdown_to_html(markdown_text: str) -> str:
    """Small safe Markdown renderer for Conv BI output.

    Args:
        markdown_text: Markdown content written by narrative/revision agents.

    Returns:
        Structured clean HTML output.
    """
    blocks: List[str] = []
    lines = markdown_text.splitlines()
    i = 0
    paragraph: List[str] = []

    def flush_paragraph() -> None:
        if paragraph:
            blocks.append(f"<p>{html.escape(' '.join(paragraph))}</p>")
            paragraph.clear()

    while i < len(lines):
        line = lines[i].rstrip()
        if not line:
            flush_paragraph()
            i += 1
            continue
        if line.startswith('### '):
            flush_paragraph(); blocks.append(f"<h3>{html.escape(line[4:])}</h3>"); i += 1; continue
        if line.startswith('## '):
            flush_paragraph(); blocks.append(f"<h2>{html.escape(line[3:])}</h2>"); i += 1; continue
        if line.startswith('# '):
            flush_paragraph(); blocks.append(f"<h1>{html.escape(line[2:])}</h1>"); i += 1; continue
        if line.startswith('|') and i + 1 < len(lines) and lines[i + 1].strip().startswith('|'):
            flush_paragraph()
            table_lines = []
            while i < len(lines) and lines[i].strip().startswith('|'):
                table_lines.append(lines[i].strip())
                i += 1
            rows = [[cell.strip() for cell in row.strip('|').split('|')] for row in table_lines]
            header = rows[0]
            body = rows[2:] if len(rows) > 2 else []
            head_html = ''.join(f"<th>{html.escape(cell)}</th>" for cell in header)
            body_html = ''.join('<tr>' + ''.join(f"<td>{html.escape(cell)}</td>" for cell in row) + '</tr>' for row in body)
            blocks.append(f"<div class='convbi-table-wrap'><table><thead><tr>{head_html}</tr></thead><tbody>{body_html}</tbody></table></div>")
            continue
        if line.startswith('- '):
            flush_paragraph()
            items = []
            while i < len(lines) and lines[i].strip().startswith('- '):
                items.append(f"<li>{html.escape(lines[i].strip()[2:])}</li>")
                i += 1
            blocks.append(f"<ul>{''.join(items)}</ul>")
            continue
        paragraph.append(line)
        i += 1
    flush_paragraph()
    return "<article class='convbi-answer-html'>" + ''.join(blocks) + "</article>"


def plan_visualizations_fallback(question: str, executed_queries: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Heuristic fallback planner when visualization planners are unavailable.

    Args:
        question: User request query.
        executed_queries: Results from executed query steps.

    Returns:
        Structured comparative or table plan.
    """
    visualizable = []
    for q in executed_queries:
        if q.get('rows') and len(q['rows']) > 0:
            visualizable.append({
                'label': q['label'],
                'row_count': q['row_count'],
                'columns': list(q['rows'][0].keys()),
                'sample': q['rows'][:3]
            })
            
    if not visualizable:
        return {'has_visual': False, 'visuals': []}

    first_ds = visualizable[0]
    first_label = first_ds['label']
    first_cols = first_ds['columns']
    first_sample = first_ds['sample'][0]
    
    numeric_cols = [k for k, v in first_sample.items() if isinstance(v, (int, float))]
    label_cols = [k for k in first_cols if k not in numeric_cols]
    
    val_col = numeric_cols[-1] if numeric_cols else 'balance'
    lbl_col = label_cols[0] if label_cols else 'branch'
    
    return {
        'has_visual': True,
        'visuals': [{
            'type': 'bar',
            'title': f'{first_label} Overview',
            'description': 'Comparative view generated automatically from operational records.',
            'data_key': first_label,
            'config': {
                'label_column': lbl_col,
                'value_column': val_col,
                'color_scheme': 'indigo',
                'is_percentage': False,
                'show_totals': True
            }
        }]
    }
